### PR TITLE
fix: direct builds to the correct client build regardless of adapter

### PR DESCRIPTION
**Pull request by rishi-raj-jain**

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@thejackshelton @steve8708

I've fixed the issue of referencing the static files into the right path. Let me know if anything.

**Comment by thejackshelton** [comment]
Looks good, merging!

**Comment by rishi-raj-jain** [comment]
Thanks @thejackshelton!

**Comment by thejackshelton** [comment]
Tested it out on Vercel and Cloudflare, looks like it's working!

With cloudflare I do see a whole ton of build/type errors

image

My guess here is because we're moving the artifacts rather than copying them?

**Comment by rishi-raj-jain** [comment]
> With cloudflare I do see a whole ton of build/type errors

Do these occur without the plugin?

**Comment by rishi-raj-jain** [comment]
Ah wait, this is not specific to the plugin but the qwik build file generated.

**Comment by rishi-raj-jain** [comment]
I think this can be safely ignored as it says "unreachable code detected" which is basically of no worries.

**Comment by rishi-raj-jain** [comment]
> Tested it out on Vercel and Cloudflare, looks like it's working!

I did test with Vercel, Netlify and Node

**Comment by thejackshelton** [comment]
> > With cloudflare I do see a whole ton of build/type errors
> 
> Do these occur without the plugin?

Ah looks like this happened without the adapter, interesting 🤔 . Either way, it's working with cloudflare. Cool stuff!

**Comment by rishi-raj-jain** [comment]
Thanks man! ✨

**Comment by thejackshelton** [comment]
@rishi-raj-jain I've included your Vercel SSR tutorial in the readme! If you could remove the outDir part of the post 👍 

https://www.npmjs.com/package/@qwikdev/astro#community-guides

**Comment by rishi-raj-jain** [comment]
@thejackshelton 

Done

**Pull request merged**
