### PR TITLE
inline component support

### PR DESCRIPTION
**Pull request by thejackshelton**

### CODE REVIEW

**Comment by siguici** [comment]
Awesome! I think this solves #142.
I tried to [open it in Stackblitz](https://pkg.pr.new/template/7089f7d7-43fa-4b29-b017-7b6384c1620f) but the default template is empty. I'll have to install Astro and Qwik before I can try it. I wonder if there's a way to set up a default starter kit with [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new) for a quick start.

**Comment by siguici** [comment]
> > I tried to [open it in Stackblitz](https://pkg.pr.new/template/7089f7d7-43fa-4b29-b017-7b6384c1620f) but the default template is empty. I'll have to install Astro and Qwik before I can try it. I wonder if there's a way to set up a default starter kit with [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new) for a quick start.
> 
> I just saw that [it's possible to do it](https://github.com/stackblitz-labs/pkg.pr.new?tab=readme-ov-file#setup) with `npx pkg-pr-new publish './packages/A' --template './examples/*'`. I 'll do it to the CI using the base template.

It's done (#152)!

**Comment by thejackshelton** [comment]
> Awesome! I think this solves #142. I tried to [open it in Stackblitz](https://pkg.pr.new/template/7089f7d7-43fa-4b29-b017-7b6384c1620f) but the default template is empty. I'll have to install Astro and Qwik before I can try it. I wonder if there's a way to set up a default starter kit with [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new) for a quick start.

I think there's a way to setup a default stackblitz template 🤔 . Would have to look into it

**Comment by thejackshelton** [comment]
> > > I tried to [open it in Stackblitz](https://pkg.pr.new/template/7089f7d7-43fa-4b29-b017-7b6384c1620f) but the default template is empty. I'll have to install Astro and Qwik before I can try it. I wonder if there's a way to set up a default starter kit with [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new) for a quick start.
> > 
> > 
> > I just saw that [it's possible to do it](https://github.com/stackblitz-labs/pkg.pr.new?tab=readme-ov-file#setup) with `npx pkg-pr-new publish './packages/A' --template './examples/*'`. I 'll do it to the CI using the base template.
> 
> It's done (#152)!

Awesome!!

**Pull request merged**
