### PR TITLE
:bug: Fix #22: Use Astro configuration source directory to map symbol and chunck.

### LINKED ISSUE #22: Qwik Integration not resolving correctly 'srcDir' from Astro config.
# Problem
The issue is actually very simple, I usually like to name my `src` dir `source` because I prefer it that way. Astro offers the possibility to change the source directory with its `srcDir` config property, and that's what i have:

```js
export default defineConfig({

  integrations: [

    // ...
    qwikdev(),
    // ...
  ],

  srcDir: 'source',
  outDir: 'build',
})
```

But as soon as I try to start developing I face this error:
```
error   Qwik srcDir "/home/iivvaannxx/...myprojectroot.../src" not found.
Error: Qwik srcDir "/home/iivvaannxx/...myprojectroot.../src" not found.
    at Object.validateSource (file:///home/iivvaannxx/...myprojectroot.../node_modules/@builder.io/qwik/optimizer.mjs:1822:17)
    at async Context.buildStart (file:///home/iivvaannxx/...myprojectroot.../node_modules/@builder.io/qwik/optimizer.mjs:3377:7)
    at async Promise.all (index 3)
    at async hookParallel (file:///home/iivvaannxx/...myprojectroot.../node_modules/vite/dist/node/chunks/dep-bb8a8339.js:43927:9)
    at async Object.buildStart (file:///home/iivvaannxx/...myprojectroot.../node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44251:13)
    at async file:///home/iivvaannxx/...myprojectroot.../node_modules/vite/dist/node/chunks/dep-bb8a8339.js:65315:13
    at async httpServer.listen (file:///home/iivvaannxx/...myprojectroot.../node_modules/vite/dist/node/chunks/dep-bb8a8339.js:65332:17)
error: script "dev" exited with code 1 (SIGHUP)
```
# Additional Information
I tried hooking a `console.log` to see if the foillowing code (from the integration) correctly resolves the path:

code

And it actually does it resolve correctly to `source` so I guess the error is somewhere else.

# Reproduction
Minimal Repro: https://stackblitz.com/edit/github-ubg8bv

A couple of things I noticed while setting up the reproduction example, which may be worth to look at are that, from a brand new Astro empty template and following the [docs installation](https://qwik.builder.io/docs/integrations/astro/) I got a random error:

```
Failed to load url fs-extra (resolved id: fs-extra) in /home/projects/github-ubg8bv/node_modules/@qwikdev/astro/src/index.ts. Does the file exist?
```
Which I fixed by manually installing `fs-extra` (~~I actually didn't need to do this in my local project so I don't understand why it happened~~ edit: It just happened too). And, after creating a simple `Counter` component (like in the docs) I received also this error:

```
Error when evaluating SSR module /home/projects/github-ubg8bv/source/pages/index.astro: failed to import "/source/components/counter.tsx"
|- Error: Optimizer should replace all usages of $() with some special syntax. If you need to create a QRL manually, use inlinedQrl() instead.
    at $ (/home/projects/github-ubg8bv/node_modules/@builder.io/qwik/core.mjs:8508:15)
    at Proxy.component$ (/home/projects/github-ubg8bv/node_modules/@builder.io/qwik/core.mjs:8650:25)
    at eval (/home/projects/github-ubg8bv/source/components/counter.tsx:7:39)
    at async instantiateModule (/home/projects/github-ubg8bv/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56104:9)

 error   Optimizer should replace all usages of $() with some special syntax. If you need to create a QRL manually, use inlinedQrl() instead.
```
This fixed itself after reloading the dev server (I think). After those I finally received the error I mention in this issue about the `srcDir`.

### PR DESCRIPTION
**Pull request by siguici**

### CODE REVIEW

**Comment by thejackshelton** [comment]
Hey @siguici! I tested out the PR and when running preview I get an error when running `pnpm preview`.

The preview URL shows me an internal server error

The check function inside of `server.ts` gives me the following error:
```
Error in check function of @qwikdev/astro:  TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/jackshelton/dev/open-source/astro/qwikdev-astro/libs/qwikdev-astro/src/index.ts
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

Also is there a reason that the astro config file has a bunch of different extensions? I see in the astro docs they tell you to use `astro.config.mjs`

**Comment by siguici** [comment]
Indeed, I just encountered the same problem. I'm on the spot.
Regarding the extensions, I got this list from [the source code of the core of the Astro configuration](https://github.com/withastro/astro/blob/main/packages/astro/src/core /config/config.ts#L82-L88) which [supports all of them](https://docs.astro.build/en/guides/configuring-astro/#supported-config-file-types). Besides, I use astro.config.ts on [my personal website](https://github.com/siguici/sigui.ci) (still in development) and it works very well.

**Comment by siguici** [comment]
I have just investigated, and the root cause of the issue stems from our use of JavaScript (for interpreting TypeScript). We will need to either switch to TypeScript or compile the production files to accommodate the use of JavaScript.

As a temporary solution, I have addressed the issue by incorporating TypeScript into Astro's configuration file.

Thank you for your feedback; it serves as valuable encouragement.

**Comment by thejackshelton** [comment]
> I have just investigated, and the root cause of the issue stems from our use of JavaScript (for interpreting TypeScript). We will need to either switch to TypeScript or compile the production files to accommodate the use of JavaScript.
> 
> Thank you for your feedback; it serves as valuable encouragement.

Hm... we are using ts in the built files because vite does all that for us I think 
https://www.npmjs.com/package/@qwikdev/astro?activeTab=code

> As a temporary solution, I have addressed the issue by incorporating TypeScript into Astro's configuration file.

Ah I see that the file name was changed to .ts and that works? I think most people would be having an `astro.config.mjs` by default though 🤔 

> Thank you for your feedback; it serves as valuable encouragement.

Of course! And massive thanks for helping out with this integration, this is not easy stuff 😅

**Comment by siguici** [comment]
> Hm... we are using ts in the built files because vite handles the build for us I think.

Exactly, Vite builds assets including TypeScript files. I'll dig deeper to see what the problem is.

> Ah I see that the file name was changed to .ts, tried that and got the same issue. I think most people would be having an `astro.config.mjs` by default though as well 🤔

I've noticed the same issue persists even after merging the provided corrections. I'll double-check everything to identify and address the root cause.
And yes, most people use `astro.config.mjs` since that is what is recommended by the documentation.

> Of course! And massive thanks for helping out with this integration, this is not easy stuff 😅

It's a real pleasure to contribute to such a project. 😊 You are doing a good job with Qwik. 👏 💪

**Comment by thejackshelton** [comment]
0.1.18 should have a fix 👍. Gonna close this for now. If there's something else I should look at let me know and I can reopen!

**Comment by siguici** [comment]
It's simply perfect 👍

**Pull request closed without merging**
